### ISSUE TITLE
Extended Docs / Support for Scenario 3 with ESDK

### ISSUE THREAD

**Issue by vib3oh** [froatsnook/meteor-shopify#15]
Trying to get this working... I posted a question on Stack Overflow, would appreciate any help from you if you can spare me some time :-)

http://stackoverflow.com/questions/35095722/meteor-shopify-authenticator-getpermanentaccesstoken-with-code

p.s. I'm using ngrok for ssl proxy, works nicely maybe add it to your guide where localhost doesn't work so well?

**Comment by dbnoble** [comment]
Quoting your authenticator code from StackOverflow for reference:

```
// I call this during 'onBeforeAction' for iron-router
function beforeAuth (query) {
    // is this necessary..?
    console.assert(Meteor.isClient);

    // get shop name like 'myshop' from 'myshop.shopify.com';
    const shop = query.shop.substring(0, query.shop.indexOf('.'));

    // use api_key stored in settings
    var api_key = Meteor.settings.public.shopify.api_key;

    // Prepare to authenticate
    var authenticator = new Shopify.PublicAppOAuthAuthenticator({
        shop: shop,
        api_key: api_key,
        keyset: 'default',
        embedded_app_sdk: true,
        redirect_uri: 'https://45a04f23.ngrok.com/testContent',
        //post_auth_uri: ???

        // This is doesn't seem to be getting
        // called after clicking through the OAuth dialog
        onAuth: function(access_token) {
            ShopifyCredentials.insert({
                shop: shop, 
                api_key: api_key, 
                access_token: access_token
            });
        }
    });

    // Should i use something different with iron-router?
    location.href = authenticator.auth_uri;

    // how do i get code in this scope???
    // authenticator.getPermanentAccessToken(code);
}
```

**Comment by dbnoble** [comment]
@ArdentKid
There are a few issues with the way you are trying to set up the authenticator, although it's not really your fault because the way Scenario 3 works in the docs is not an 'out of the box' solution and requires a bunch of custom code, including your own handler (I can provide a gist if you REALLY want to build your own handler, but I suggest using the new server-side `onAuth` callback instead)

**1.** Specifying a `redirect_uri` overrides the package's default redirect_uri handler which is `Meteor.absoluteUrl("/__shopify-auth")`, unless you want to build your own handler, you should leave this and let the package's handler take care of it. 

So instead, completely remove `redirect_uri` and put your testContent url in `post_auth_uri` instead. 

**2.** ShopifyCredentials does not exist in this package. If you want to use it that way, make sure you actually have defined a collection called 'ShopifyCredentials' and insert the record from the server, not the client. Note that you will still need to add a keyset _on the server_ for the API methods to work. If you are using user accounts and would like to permanently strore credentials, I suggest saving the credentials to the database and adding the keyset via a server-side onAuth callback.

**3.** `authenticator.getPermanentAccessToken(code)` isn't useful unless you are using your own handler. Instead, you can just get `access_token` from the `onAuth` callback. 

Also keep in mind that if you ever need to reauthenticate from inside the embedded app, you need to use `window.top.location.href` to break out of the iframe.

If you want a complete, working boilerplate example _with user accounts_ see my gist here:
[Authentication with Accounts and Persistent Keysets](https://gist.github.com/dbnoble/8867b392f89462732495)

If you aren't using accounts, you can use this gist instead, but please note that you really need to come up with some way to check that the current client has permission to request the keyset for a given shop before going to production:
[Authentication with Persistent Keysets](https://gist.github.com/dbnoble/1120dafcf44cc8f60f46)

**Comment by vib3oh** [comment]
Very grateful for your help! Just a couple followup q's:

1) Assuming I want to create users upon authorizing the app, how would I grab their email during the onAuth callback...? Looks like the callback assumes the user is already logged in. [Stack Overflow Here](http://stackoverflow.com/questions/35107573/meteor-shopify-user-creation-login-after-auth-callback)

2) If I use post_auth_uri to redirect to my testContent page, don't I still need to assign it to `https://${shop}.myshopify.com/admin/apps/${api_key}` to get the access token?

**Comment by dbnoble** [comment]
@ArdentKid

**1.** The user's email can be be extracted directly via the API by making a call to retrieve the shop object. You can do something like below in your server-side onAuth callback (untested, rough example) :

```
Shopify.onAuth(function(access_token, authConfig, userId) {
  var shopUUID = uuid.new();
  var existingShop = Shops.findOne({shop: authConfig.shop}); 
  if(existingShop) {
    shopUUID = existingShop.locator;
    // if the shop exists, it should already belong a user, so we can use that userId.
    userId = existingShop.userId;
  }

  Shopify.addKeyset(shopUUID, {
    access_token: access_token
  });

  Keysets.upsert({name: shopUUID}, {$set: { token: access_token }});

  // If there's still no userId set, we'll grab it from the API and
  // either find the existing user or create one
  if(!userId){
    var email = 'not@specified.com'; // set a dummy value to overwrite
    var api = new Shopify.API({
      shop: authConfig.shop,
      keyset: shopUUID
    });
    // get the Shop object from the API
    var shopObj = api.getShop();
    email = shopObj.email;

    // search for existing user with that email
    var existingUser = Meteor.users.findOne({email: email});

    if(!existingUser) {
      // create a new user with the email address and set userId to returned value
      // I have no idea what your requirements for accounts are, so I can't provide
      // example code for this. Look into Accounts.createOrUpdateUserFromExternalService
    userId = function_That_Creates_A_User_And_Returns_The_Id();
    } else {
      // if a user does exist with that email address, set userId to that user's _id
      userId = existingUser._id;
    }
  }

 // Finally we can update the shop and associate it with the user
  Shops.update({shop: authConfig.shop, userId: userId}, {
    $set: {
      locator: shopUUID
    },
  }, {upsert: true});

});
```

You'll still need to figure out a way to log the user in afterwards and all that. You should also consider that it's quite likely that a user might have different emails for different shops, so emails are not necessarily the best vector for identification. It would probably be better to always allow users to authenticate and then handle what happens next conditionally based on their login status. If no `userId` is present in the `onAuth` callback, temporarily save the authentication details to a collection called something like `Unassigned`, forward the user to a login form, and then associate the user/shop relationship after they have logged in/signed up. That would solve alot of issues like when a user authenticates to a new shop from a different device or browser and is not logged in, has different email addresses assigned to multiple shops, etc.

Before the server-side onAuth existed, I built a custom handler and gateway page that did all of that junk based only the current shop, but overall I think it's a little bit too convoluted. Modifying it so that multiple shops can be assigned to the same user would probably be a better way instead of a 1:1 user/shop relationship, but again you'll run into issues determining when you should create a new user vs modifying an existing one. At the time I was using iron router, if you are using FlowRouter you'll need to add a server-side router like Picker to handle your server-side request routes. You can see the rundown here:
https://github.com/froatsnook/meteor-shopify/issues/9#issuecomment-156478861

I'm not going to lie, if you want to do passwordless accounts that get created at auth, there are alot of potential edge cases to think about. I have built it that way before, and it seems to work okay, but I'm still concerned that there are edge cases that I didn't think of that would cause some issues. For instance, Meteor stores user's `loginToken` in `localStorage` instead of in the `Session`... so what happens when the same user has your app installed on two shops and tries to use them both simultaneously in different tabs?

It also makes me feel uneasy identifying a user based only on the shop parameter. Alot of complexity is introduced in terms of making sure that it's a valid request. If you're using the shop param, checking the referrer, and verifying the authenticity of the HMAC it's probably decently secure but there's just alot of moving parts to do it this way and it feels 'dirty'.

**2.** I apologize for the confusion. I don't even know why I said that. I meant to say that the `after_auth_uri` should point to the app, so yes `https://${shop}.myshopify.com/admin/apps/${api_key}` would be the correct pattern here. You COULD instead redirect them to an account sign up page or something instead and have them create an actual user account with a password if you wanted.

I also want to point out that `post_auth_uri` has nothing to do with the authentication, it's simply where you want them to go well.... post auth! By the time a user lands at `post_auth_uri`, all the oAuth related stuff will have already been taken care of.

I'll break down the flow for you so you can see what's actually happening here:
1. User goes to install your app
2. User is sent to Shopify's auth dialog
3. Shopify sends an auth response with access token to the `redirect_uri` (the handler)
4. The handler verifies the auth response from Shopify
5. If the auth request is valid it fires `onAuth` callbacks with the necessary params
6. User is redirected to the `post_auth_uri`

3-5 happens basically instantly and is not really observable. Everything you need to do with the access token should be happening in your onAuth callbacks.

**Comment by vib3oh** [comment]
Pure genius, cannot thank you enough for the help you've given me!

Regarding the `post_auth_uri` however, something's still missing from my understanding. How do I know if the shop owner has already done auth? If my "Application Url" set in shopify settings is my home path "/", and this path has the authenticator defined with `post_auth_uri`, to `https://${shop}.myshopify.com/admin/apps/${api_key}` then how do I tell it after auth to go to "/testContent" instead? 

Right now, i'm getting an infinte loop where it keeps trying to hit "/" and re-authenticate.

**Comment by dbnoble** [comment]
Well, that's a bit hard to answer because it's totally dependent on how you have things set up.

You can define your authenticator in your entry route and simply do the necessary checks in the route to see if the user has already authenticated. If they haven't, authenticate. If they have, proceed as usual.

If you don't have anything other than the  authenticator at `/` there's not really a reason to set that as the home path for the embedded app while your actual main page is at `/someOtherRoute`. I'd say move the authenticator into the testContent route and just set that as the home path.

Keep in mind, with an embedded app, things work a little differently anyway. If a user has not authenticated, the app doesn't actually appear in the 'Apps' area of the shop. Once a user has authenticated, the only time you would need to reauthenticate is if the client's token is invalidated for whatever reason, you need to request additional scope permissions, or if you are not storing the access token in the DB. 

That means that anyone hitting your home path will have already had to authenticated in the past, otherwise there would be no way to load the app in the first place.

If you can tell me a little more about your setup I can give a better answer. User accounts or no? Saving Shops on the DB? How are you naming your keyset? 

It's probably better to focus on getting one little piece to do what you want and then move on to the next so that you're getting a very tactile experience with what you change vs the resulting functionality.

**Comment by dbnoble** [comment]
Also, don't feel bad that you're not fully "getting it" yet. 2 months ago I was in the same boat, now I'm about 2 weeks away from releasing a production app built around this package and I'm very happy with it.

One of the things I'd like to contribute in the coming months is streamlining and simplifying the documentation so that things are more clear.

**Comment by froatsnook** [comment]
> One of the things I'd like to contribute in the coming months is streamlining and simplifying the documentation so that things are more clear.

Sounds good to me :)

**Comment by vib3oh** [comment]
@dbnoble i've got it working :)
1) I set up my Application Url to the home path, `/` and on the client it calls a meteor method to check if the keyset of the shop exists.
2) If the keyset exists, redirect to `/shopify` (where my content is)
3) If not, it redirects to `/shopify/auth` for the OAuth dialog

I'm also storing user info, although I'm ignoring a few edge cases that you've mentioned. I decided for v1 it'll be good enough and just do user auth from their email, without a login/ register form. (Not going to be concerned about users with more than one shop for now).

Thank you for all the help and i'd be thrilled to Skype with you to talk about the project i'm working on. I'm going through a Startup accelerator right now in San Francisco and we're trying to launch our platform on Shopify asap. Feel free to message me on Twitter @ArdentKid and I'll send you my email/ Skype!

**Comment by froatsnook** [comment]
@ArdentKid, hopefully your auth flow can be improved soon!  Shopify sends (I think) `code`, `signature`, and `shop` -- everything you need to get the `access_token` -- with the first navigation.  I haven't dug into this yet since the project I built this package for was more of a "click here to get data from shopify" (shopify integration), and not a "install it from shopify app store".

I'm closing this issue for now, but feel free to re-open or open a new issue.

Thanks @dbnoble for sharing your expertise.

**Comment by froatsnook** [comment]
BTW, I'd love to hear about your project.  Write me on twitter or gmail (my user name) if you have time.
