### ISSUE TITLE
Access Token

### ISSUE THREAD

**Issue by ilrein** [froatsnook/meteor-shopify#2]
Hey @froatsnook, thanks for updating the package and implementing the embedded app feature!

I've been studying your example application, and I can successfully load my app as an iFrame in the Shopify dashboard! Very exciting.

So my next logical step was to actually pull some data from my store to do stuff. Which is where I need some assistance...

For example, I tried this:

 ` 'click #test': function() {

```
var authenticater = new Shopify.PublicAppOAuthAuthenticator({
  shop: "shop",
  api_key: "7axxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  keyset: "default",
  scopes: "read_content,read_products",
  embedded_app_sdk: true,
  onAuth: function(accessToken) {
    Meteor.users.update(Meteor.userId(), {
      $set: { "profile.shopifyAccessToken": access_token }
    });
  }
});
authenticater.openAuthTab();
```

  }`

Which results in: `Exception in delivering result of invoking 'froatsnook:shopify/HandleAuthRedirect': ReferenceError: access_token is not defined`.

If perhaps you could consider updating the sample embed application to also do an API call, like `countOrders()`, I think that would be immensely helpful. 

I'm worried that my lack of experience with Shopify is potentially causing me to ask dumb questions. Like, I do need an access token right? Even if the app is an iframe in the dashboard? 

When I look at my ShopifyApp object, I see that `_autenticator` is `null`...

Should I be trying to get access to `var api = new Shopify.API({...` in the `Shopify.getEmbeddedAppAPI` callback?

Sorry for the semi-rambling. Still trying to wrap my head around all this.

**Comment by froatsnook** [comment]
Hey @ilrein.  I'm glad you were able to load it in the dashboard.

This Exception is actually something very easy!  In the `onAuth` callback the parameter is called `accessToken`, but then later you refer to it as `access_token`.  This has bitten me before too since I normally camelCase but shopify likes to snake_case.  Sometimes they even camel case, as you'll see below!

I have no experience with the Embedded App SDK, which is why things are a bit half-baked in this version.  Here's how I would describe the current setup:
- `Shopify.API` is the original API (that I made, making use of the Shopify API) which is useful for things like counting orders.  You can use this client- or server-side.
- `ShopifyApp` is a javascript API that Shopify made which can only be used from the iframe, and which is useful for doing things like showing messages and creating a UI within the iframe
- You probably need to create both to make a useful app, and each needs to be initialized separately:

``` javascript
onAuth: function(accessToken) {
    // initialize meteor-shopify
    var api = new Shopify.API({
        shop: "shop",
        access_token: accessToken,
        insecure: true // I have to think more about this and whether it should be necessary.  For now include it when doing EASDK stuff!
    });

    // Initialize EASDK
    Shopify.getEmbeddedAppSDK(function(err, ShopifyApp) {
        ShopifyApp.init({
            apiKey: "7axxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            shopOrigin: "https://shop.myshopify.com"
        });
    });
  }
```

In order to help you understand this authentication stuff I should say this:
- `ShopifyApp` (for EASDK) doesn't need the access_token in the iframe.  I guess it has a cookie for this.
- `Shopify.API` adds the access_token to every single request in `"X-Shopify-Access-Token"` header.  This means that you have to provide it when you create it.  It also means that you can use it on the client and the server!

Is this making more sense now?  Any suggestions on how I can improve the docs?

**Comment by froatsnook** [comment]
I will update the example.

EDIT: Done!  That was a good idea.

**Comment by ilrein** [comment]
@froatsnook thanks so much, for all your help! I'm digging into your answer, reviewing the sample app, and adjusting my own app. I'll let know how to streamline the docs once I get everything rolling. I'm so close, I can taste it!

EDIT: _BAM_ I got some data! We are officially a go!

So, quick takeaway, `var api` needs to be defined outside of `getEmbeddedAppAPI`, and then you can use its method calls within `getEmbeddedAppAPI`.

I'd be happy to contribute a quick visual tutorial on going from 0 to embedded Meteor app, with some presentation JS library. Right now I'm pretty excited to work on this app, but you'll hear from me again!

**Comment by froatsnook** [comment]
@ilrein Great that it's working.

And a visual tutorial like that would be great.  Even just screenshots would be nice.

Good luck with your project :).  Maybe we can add a logo to the README when you go live?
