### ISSUE TITLE
OAuth HMAC Verification

### ISSUE THREAD

**Issue by lukeclifton** [froatsnook/meteor-shopify#5]
Hey.

Great to see this package for using Shopify with Meteor. I created a package with a similar goal but it was my first attempt and pretty bad, so i want to re-write.

One question regards your package...i can't see anywhere in the code that your doing any kind of HMAC verification. Am i missing it or is it yet to be added?
https://docs.shopify.com/api/authentication/oauth#verification

Thanks,

Luke

**Comment by froatsnook** [comment]
OK if I understood that correctly, the HMAC verification is to check that responses from Shopify haven't been MITMed.  This isn't something that I've implemented.  I never thought about this since it's an https connection anyway.  For my usage it's not necessary, but if someone requests it, then I'll implement it.  It doesn't look too complicated.

**Comment by froatsnook** [comment]
1.6.0 with signature checking is published.  Thanks for your help with this one.
