### ISSUE TITLE
Storing access token in users profile

### ISSUE THREAD

**Issue by lukeclifton** [froatsnook/meteor-shopify#6]
Sorry me again. :)

I noticed that upon generating the permanent access token, your storing it on the users profile object.

I may be wrong but i'm pretty sure this is not recommended as the users profile object is always published to the client and is insecure.

https://meteor.hackpad.com/Proposal-for-deprecating-user-profile-3UljX1VayvV

I think the way to do it is via the core service configuration package?
https://atmospherejs.com/meteor/service-configuration

Sorry if i wrong and don't know what i'm talking about, i'm still learning but just wanted to get your opinion on it as the rest of your package looks great.

**Comment by froatsnook** [comment]
Where did you see it stored in the user's profile?  I might have done that for simplicity in an example app?  The normal way is to use `Shopify.addKeyset`, and then everything lives on the server (requests from the client are proxied).

I think it's probably not the best idea to store it in the user profile since someone could mess up your app's rate limiting or something.  It would be worse to store other secrets on the client side.
